### ISSUE TITLE
Better examples?

### ISSUE THREAD

**Issue by mlenser** [devshorts/ytools#1]
It's difficult to understand how this should be used. It sounds simple, but without examples it's not so clear.

Could you perhaps add an example to eslint only packages that have changed?

**Comment by devshorts** [comment]
I can add some examples later but if you just ytools at the root it will do a diff from your current branch to master and emit json that indicates what has changed.  You can then use this metadata however you want in whatever build process you use. 

I use the output to pipe to wsrun which allows you to specify to run commands against certain yarn packages
