### ISSUE TITLE
doesn't work with yarn classic. not mentioned.

### ISSUE THREAD

**Issue by airtonix** [devshorts/ytools#7]
https://github.com/devshorts/ytools/blob/master/src/tools.ts#L74-L76

Either needs mentioning or another way needs to be found to list the workspaces.

trivial first step might be to use [`@manypkg/get-packages`](https://github.com/Thinkmill/manypkg/tree/master/packages/get-packages).

```es6
import { getPackages, getPackagesSync, Packages } from "@manypkg/get-packages";

export function yarnWorkspaceInfo(cwd?: string): Workspace {
  const { packages } = getPackagesSync(cwd);
  return packages.reduce<Record<string, Project>>((result, package) => {
    return {
      ...result,
      [package.packageJson.name]: {
        location: package.dir,
        name: package.packageJson.name, 
        workspaceDependencies: package.packageJson.dependancies,
        mismatchedWorkspaceDependencies: ???
      }
  }, {});
}
```

**Comment by devshorts** [comment]
Version 1.x works with yarn classic. 2.x works with yarn 2. I’ll mention in the readme. Will not be supporting yarn 1 as yarn 1 is also being unsupported.

thanks for opening an issue!
